//! LaTeX generation for the milestone-2 semantic subset (metadata, inline
//! markup, headings, paragraphs). No implicit dates, no absolute paths, no
//! timestamps: same module always produces the same bytes.

pub mod bibliography;
pub mod escape;
pub mod source_map;

use crate::semantic::{
    build_symbol_table, has_bibliography, Citation, CiteItem, DocumentMetadata, ListItem, Node, NodeKind,
    ParsedModule, SymbolKind, SymbolTable, TheoremKind,
};
use crate::syntax::inlines::Inline;
use crate::theme::ResolvedTheme;

pub const EMPTY_BIBLIOGRAPHY: &str = "";

pub fn generate_document(module: &ParsedModule, _theme: &ResolvedTheme) -> String {
    let symbols = build_symbol_table(module);
    let mut out = String::new();
    out.push_str("% Generated by terse. Do not edit by hand: the next successful build\n");
    out.push_str("% replaces this file. Copy it elsewhere to edit independently.\n");
    out.push_str("\\documentclass{article}\n");
    out.push_str("\\usepackage{terse-style}\n");
    if has_bibliography(module) {
        out.push_str("\\addbibresource{references.bib}\n");
    }
    if let Some(metadata) = &module.metadata {
        render_pdf_metadata(metadata, &mut out);
    }
    out.push_str("\\begin{document}\n");

    if let Some(metadata) = &module.metadata {
        render_title_material(metadata, &mut out);
    }

    render_nodes(&module.blocks, &symbols, &mut out);

    out.push_str("\\end{document}\n");
    out
}

/// PDF `/Title` and `/Author` document properties (`hyperref`'s
/// `\hypersetup`), distinct from the visible cover text rendered by
/// [`render_title_material`]: this is metadata a PDF viewer or search
/// index reads without opening the visible first page.
fn render_pdf_metadata(metadata: &DocumentMetadata, out: &mut String) {
    let authors: String = metadata
        .authors
        .iter()
        .map(|a| escape::escape_pdf_meta(&a.name))
        .collect::<Vec<_>>()
        .join(", ");
    out.push_str(&format!(
        "\\hypersetup{{pdftitle={{{}}},pdfauthor={{{}}}}}\n",
        escape::escape_pdf_meta(&metadata.title),
        authors
    ));
}

fn render_nodes(nodes: &[Node], symbols: &SymbolTable, out: &mut String) {
    for node in nodes {
        render_node(node, symbols, out);
    }
}

fn render_node(node: &Node, symbols: &SymbolTable, out: &mut String) {
    match &node.kind {
        NodeKind::Heading { level, id, inlines } => {
            let macro_name = match level {
                1 => "\\TerseHeadingOne",
                2 => "\\TerseHeadingTwo",
                _ => "\\TerseHeadingThree",
            };
            out.push_str(macro_name);
            out.push('{');
            render_inlines(inlines, symbols, out);
            out.push_str("}\n");
            if let Some(id) = id {
                out.push_str(&format!("\\phantomsection\\label{{{id}}}\n"));
            }
        }
        NodeKind::Paragraph { inlines } => {
            render_inlines(inlines, symbols, out);
            out.push_str("\n\n");
        }
        NodeKind::List { ordered, start, items } => render_list(*ordered, *start, items, symbols, out),
        NodeKind::Equation { id, payload } => {
            out.push_str("\\begin{TerseEquation}");
            if let Some(id) = id {
                out.push_str(&format!("\\label{{{id}}}"));
            }
            out.push('\n');
            out.push_str(payload);
            out.push('\n');
            out.push_str("\\end{TerseEquation}\n");
        }
        NodeKind::Figure {
            path,
            id,
            role,
            caption,
            alt,
        } => {
            let is_wide = role.as_deref() == Some("wide");
            let env = if is_wide { "figure*" } else { "figure" };
            // Width is a theme-parameterized style macro, not a literal
            // number here, so switching themes never changes this file's
            // bytes: only `terse-style.sty` decides what each role means.
            let width_macro = if is_wide {
                "\\TerseFigureWideWidth"
            } else {
                "\\TerseFigureWidth"
            };
            out.push_str(&format!("\\begin{{{env}}}[htbp]\n\\centering\n"));
            out.push_str(&format!(
                "\\includegraphics[width={width_macro}]{{{}}}\n",
                escape::escape_url(path)
            ));
            out.push_str("\\caption{");
            render_inlines(caption, symbols, out);
            out.push_str("}\n");
            // Alt text has no visual LaTeX rendering; it is retained in the
            // semantic model for accessibility tooling built on top of the
            // generated PDF (not yet part of this milestone's backend).
            let _ = alt;
            if let Some(id) = id {
                out.push_str(&format!("\\label{{{id}}}\n"));
            }
            out.push_str(&format!("\\end{{{env}}}\n"));
        }
        NodeKind::Table {
            id,
            caption,
            header,
            rows,
        } => {
            let col_spec = "l".repeat(header.len());
            out.push_str("\\begin{table}[htbp]\n\\centering\n");
            out.push_str(&format!("\\begin{{tabular}}{{{col_spec}}}\n\\toprule\n"));
            out.push_str(&render_table_row(header));
            out.push_str(" \\\\\n\\midrule\n");
            for row in rows {
                out.push_str(&render_table_row(row));
                out.push_str(" \\\\\n");
            }
            out.push_str("\\bottomrule\n\\end{tabular}\n");
            out.push_str(&format!("\\caption{{{}}}\n", escape::escape_text(caption)));
            if let Some(id) = id {
                out.push_str(&format!("\\label{{{id}}}\n"));
            }
            out.push_str("\\end{table}\n");
        }
        NodeKind::TheoremLike { kind, title, id, body } => {
            let env = theorem_environment(*kind);
            out.push_str(&format!("\\begin{{{env}}}"));
            if let Some(title) = title {
                out.push('[');
                out.push_str(&escape::escape_optional_arg(title));
                out.push(']');
            }
            out.push('\n');
            if let Some(id) = id {
                out.push_str(&format!("\\label{{{id}}}\n"));
            }
            render_nodes(body, symbols, out);
            out.push_str(&format!("\\end{{{env}}}\n"));
        }
        NodeKind::RawTex { payload } => {
            // Opaque escape hatch: emitted byte-for-byte, never escaped or
            // otherwise rewritten. Portability is the author's
            // responsibility (task group 8's W-TEX-001 strict warning).
            out.push_str(payload);
            out.push('\n');
        }
        NodeKind::Proof { id, of, body } => {
            out.push_str("\\begin{proof}\n");
            if let Some(id) = id {
                out.push_str(&format!("\\label{{{id}}}\n"));
            }
            // `of` records an explicit theorem relationship without
            // inferring one from adjacency; amsthm's `proof` environment
            // has no built-in numbering hook for it, so it is retained as
            // a source comment for now.
            if let Some(of) = of {
                out.push_str(&format!("% proof of: {of}\n"));
            }
            render_nodes(body, symbols, out);
            out.push_str("\\end{proof}\n");
        }
        NodeKind::Bibliography => {
            out.push_str("\\printbibliography\n");
        }
    }
}

fn render_table_row(cells: &[String]) -> String {
    cells
        .iter()
        .map(|c| escape::escape_text(c))
        .collect::<Vec<_>>()
        .join(" & ")
}

fn theorem_environment(kind: TheoremKind) -> &'static str {
    match kind {
        TheoremKind::Theorem => "tersetheorem",
        TheoremKind::Proposition => "terseproposition",
        TheoremKind::Lemma => "terselemma",
        TheoremKind::Definition => "tersedefinition",
        TheoremKind::Example => "terseexample",
        TheoremKind::Remark => "terseremark",
    }
}

fn render_list(ordered: bool, start: Option<u32>, items: &[ListItem], symbols: &SymbolTable, out: &mut String) {
    let env = if ordered { "enumerate" } else { "itemize" };
    match (ordered, start) {
        (true, Some(n)) if n != 1 => out.push_str(&format!("\\begin{{{env}}}[start={n}]\n")),
        _ => out.push_str(&format!("\\begin{{{env}}}\n")),
    }
    for item in items {
        out.push_str("\\item ");
        render_inlines(&item.inlines, symbols, out);
        out.push('\n');
        render_nodes(&item.continuation, symbols, out);
    }
    out.push_str(&format!("\\end{{{env}}}\n"));
}

// Metadata renders in fixed semantic order: title, subtitle,
// authors/affiliations, explicit date, abstract, keywords, then body.
fn render_title_material(metadata: &DocumentMetadata, out: &mut String) {
    out.push_str(&format!(
        "\\TerseTitle{{{}}}\n",
        escape::escape_text(&metadata.title)
    ));
    if let Some(subtitle) = &metadata.subtitle {
        out.push_str(&format!(
            "\\TerseSubtitle{{{}}}\n",
            escape::escape_text(subtitle)
        ));
    }
    for author in &metadata.authors {
        out.push_str(&format!(
            "\\TerseAuthor{{{}}}",
            escape::escape_text(&author.name)
        ));
        match &author.affiliation {
            Some(crate::semantic::Affiliation::Single(a)) => {
                out.push_str(&format!("{{{}}}", escape::escape_text(a)));
            }
            Some(crate::semantic::Affiliation::Multiple(list)) => {
                let joined = list
                    .iter()
                    .map(|a| escape::escape_text(a))
                    .collect::<Vec<_>>()
                    .join("; ");
                out.push_str(&format!("{{{joined}}}"));
            }
            None => out.push_str("{}"),
        }
        out.push('\n');
    }
    for affiliation in &metadata.affiliations {
        out.push_str(&format!(
            "\\TerseAffiliation{{{}}}\n",
            escape::escape_text(affiliation)
        ));
    }
    if let Some(date) = &metadata.date {
        out.push_str(&format!("\\TerseDate{{{}}}\n", escape::escape_text(date)));
    }
    if !metadata.abstract_blocks.is_empty() {
        out.push_str("\\begin{TerseAbstract}\n");
        for paragraph in &metadata.abstract_blocks {
            render_inlines(paragraph, &SymbolTable::new(), out);
            out.push_str("\n\n");
        }
        out.push_str("\\end{TerseAbstract}\n");
    }
    if !metadata.keywords.is_empty() {
        let joined = metadata
            .keywords
            .iter()
            .map(|k| escape::escape_text(k))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!("\\TerseKeywords{{{joined}}}\n"));
    }
}

fn render_inlines(inlines: &[Inline], symbols: &SymbolTable, out: &mut String) {
    for inline in inlines {
        render_inline(inline, symbols, out);
    }
}

fn render_inline(inline: &Inline, symbols: &SymbolTable, out: &mut String) {
    match inline {
        Inline::Text(t) => out.push_str(&escape::escape_text(t)),
        Inline::Emphasis(v) => {
            out.push_str("\\emph{");
            render_inlines(v, symbols, out);
            out.push('}');
        }
        Inline::Strong(v) => {
            out.push_str("\\textbf{");
            render_inlines(v, symbols, out);
            out.push('}');
        }
        Inline::Code(t) => {
            out.push_str("\\texttt{");
            out.push_str(&escape::escape_text(t));
            out.push('}');
        }
        Inline::Link { label, destination } => {
            out.push_str("\\href{");
            out.push_str(&escape::escape_url(destination));
            out.push_str("}{");
            render_inlines(label, symbols, out);
            out.push('}');
        }
        Inline::Footnote(v) => {
            out.push_str("\\footnote{");
            render_inlines(v, symbols, out);
            out.push('}');
        }
        Inline::Math(t) => {
            out.push_str("\\(");
            out.push_str(t);
            out.push_str("\\)");
        }
        // A heading target has no visible number to point at, so its
        // cross-reference displays the heading's own title text as a
        // hyperlink instead of a numeric `\ref`; every other kind
        // resolves to an ordinary numbered reference. Cross-file
        // resolution is task group 12's extension of this same table.
        Inline::CrossRef(id) => match symbols.get(id) {
            Some(SymbolKind::Heading(title)) => {
                out.push_str("\\hyperref[");
                out.push_str(id);
                out.push_str("]{");
                render_inlines(title, symbols, out);
                out.push('}');
            }
            Some(SymbolKind::Numbered) | None => {
                out.push_str("\\Terseref{");
                out.push_str(id);
                out.push('}');
            }
        },
        Inline::Citation(citation) => render_citation(citation, out),
    }
}

fn locator_arg(item: &CiteItem) -> String {
    match &item.locator {
        Some(locator) => format!("[{}]", escape::escape_optional_arg(&locator.raw)),
        None => String::new(),
    }
}

fn render_citation(citation: &Citation, out: &mut String) {
    match citation {
        Citation::Narrative(alias) => {
            out.push_str("\\textcite{");
            out.push_str(alias);
            out.push('}');
        }
        // A single work uses BibLaTeX's ordinary `\cite[locator]{key}`;
        // more than one uses `\cites`, BibLaTeX's dedicated multicite
        // macro, so each work keeps its own independent locator rather
        // than sharing one postnote across a comma list.
        Citation::Group(items) if items.len() == 1 => {
            out.push_str("\\cite");
            out.push_str(&locator_arg(&items[0]));
            out.push('{');
            out.push_str(&items[0].alias);
            out.push('}');
        }
        Citation::Group(items) => {
            out.push_str("\\cites");
            for item in items {
                out.push_str(&locator_arg(item));
                out.push('{');
                out.push_str(&item.alias);
                out.push('}');
            }
        }
    }
}

/// Package names Terse recognizes as built-in declared support (`terse.toml`
/// `[latex] packages`). Each maps directly to a `\RequirePackage`; there is
/// no other declaration syntax for these, and unknown names are rejected by
/// [`validate_packages`] before this function is ever reached.
pub const BUILTIN_PACKAGES: &[&str] = &["tikz"];

/// Every package name [`generate_style`] can ever `\RequirePackage`, apart
/// from the theme's font package (those are listed by the export profile
/// under `fonts`): the always-loaded core set, the citation-build set, the
/// watermark set, and the closed built-in registry. The export profile's
/// `packages` list must equal this set exactly; a profile entry the
/// generator never emits would make `compiled-profile` claim more than it
/// checked, and an emitted package missing from the profile would make a
/// valid document fail export validation.
pub const STYLE_PACKAGES: &[&str] = &[
    "fontspec",
    "amsmath",
    "amsthm",
    "graphicx",
    "booktabs",
    "enumitem",
    "hyperref",
    "babel",
    "biblatex",
    "eso-pic",
    "tikz",
];

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct UnknownPackage(pub String);

/// Validates declared `[latex] packages` entries against the closed
/// built-in registry, preserving authored order and rejecting duplicates
/// only implicitly (a package required twice is harmless, but an unknown
/// name always fails before any generation or engine invocation).
pub fn validate_packages(packages: &[String]) -> Result<Vec<&'static str>, UnknownPackage> {
    let mut out = Vec::new();
    for p in packages {
        match BUILTIN_PACKAGES.iter().find(|&&b| b == p) {
            Some(&name) => out.push(name),
            None => return Err(UnknownPackage(p.clone())),
        }
    }
    Ok(out)
}

/// Maps a theme's versioned, stable body-font token to the actual
/// TeX-distributed package name that provides it. The token itself (not
/// this mapping) is what a `.theme` file declares and what
/// [`ResolvedTheme`] stores, so the package this loads can change without
/// touching any authored theme.
pub fn font_package_for(token: &str) -> &str {
    match token {
        "tex-gyre-heros" => "tgheros",
        "tex-gyre-pagella" => "tgpagella",
        "latin-modern" => "lmodern",
        other => other,
    }
}

/// Maps a document's `language` metadata field (validated to `en` or
/// `pt-BR` during lowering) to the Babel/BibLaTeX language identifier
/// that selects hyphenation patterns and localized strings (bibliography
/// heading, date formatting) — never the running OS's installed locale.
fn babel_language_for(document_language: &str) -> &'static str {
    match document_language {
        "pt-BR" => "brazilian",
        _ => "english",
    }
}

pub fn generate_style(theme: &ResolvedTheme, extra_packages: &[&str], bibliography_language: Option<&str>) -> String {
    let extra: String = extra_packages
        .iter()
        .map(|p| format!("\\RequirePackage{{{p}}}\n"))
        .collect();
    // Biber only runs for citation builds (task 16.3): a module with no
    // bibliography never loads BibLaTeX/Babel at all, so it never depends
    // on Biber or locale hyphenation patterns it does not need.
    let bibliography_setup = match bibliography_language {
        Some(language) => format!(
            "\\RequirePackage[main={babel_lang}]{{babel}}\n\
\\RequirePackage[backend=biber,sorting=none,language={babel_lang}]{{biblatex}}\n",
            babel_lang = babel_language_for(language),
        ),
        None => String::new(),
    };
    let watermark = if theme.watermark_kind == "none" {
        String::new()
    } else {
        let label = match theme.watermark_kind.as_str() {
            "draft" => "DRAFT",
            _ => "INTERNAL USE",
        };
        // A true alpha-blended watermark needs the `transparent` package,
        // which requires a pdfTeX-mode driver check that does not hold
        // under XeLaTeX in this toolchain; a light gray level (lower
        // opacity -> closer to white, i.e. fainter) gives the same
        // "visible but unobtrusive background furniture" effect without
        // that dependency.
        let gray_level = (1.0 - theme.watermark_opacity).clamp(0.0, 1.0);
        format!(
            "\\RequirePackage{{eso-pic}}\n\
\\AddToShipoutPictureBG{{\\AtPageCenter{{\\makebox(0,0){{\\rotatebox{{{angle}}}{{\\fontsize{{60}}{{60}}\\selectfont\\textcolor[gray]{{{gray_level}}}{{{label}}}}}}}}}}}\n",
            angle = theme.watermark_angle,
            gray_level = gray_level,
            label = label,
        )
    };
    let logo = match &theme.logo_path {
        Some(path) => format!(
            "\\newcommand{{\\TerseLogo}}{{\\includegraphics[width={pct}\\linewidth]{{{path}}}}}\n",
            pct = f64::from(theme.logo_width_pct) / 100.0,
        ),
        None => "\\newcommand{\\TerseLogo}{}\n".to_string(),
    };
    let heading_sizes = ["\\Large", "\\large", "\\normalsize"];
    let heading_counters = ["terseheadingone", "terseheadingtwo", "terseheadingthree"];
    let heading_macros = ["TerseHeadingOne", "TerseHeadingTwo", "TerseHeadingThree"];
    let mut headings = String::new();
    for i in 0..3 {
        let counter = heading_counters[i];
        headings.push_str(&format!("\\newcounter{{{counter}}}\n"));
        let number_prefix = match theme.heading_numbering[i].as_str() {
            "decimal" => format!("\\arabic{{{counter}}}.\\ "),
            "roman" => format!("\\Roman{{{counter}}}.\\ "),
            _ => String::new(),
        };
        headings.push_str(&format!(
            "\\newcommand{{\\{macro_name}}}[1]{{\\refstepcounter{{{counter}}}\\par\\vspace{{1em}}{{{size}\\{weight}\\selectfont {number_prefix}#1}}\\par}}\n",
            macro_name = heading_macros[i],
            size = heading_sizes[i],
            weight = theme.heading_weight[i],
        ));
    }
    let figure_widths = format!(
        "\\newcommand{{\\TerseFigureWidth}}{{{default:.3}\\linewidth}}\n\\newcommand{{\\TerseFigureWideWidth}}{{{wide:.3}\\linewidth}}\n",
        default = f64::from(theme.figure_default_width_pct) / 100.0,
        wide = f64::from(theme.figure_wide_width_pct) / 100.0,
    );
    format!(
        "% Generated by terse for theme '{name}'. Do not edit by hand.\n\
\\NeedsTeXFormat{{LaTeX2e}}\n\
\\ProvidesPackage{{terse-style}}\n\
\\RequirePackage{{fontspec}}\n\
\\RequirePackage{{{font_package}}}\n\
\\RequirePackage{{amsmath}}\n\
\\RequirePackage{{amsthm}}\n\
\\RequirePackage{{graphicx}}\n\
\\RequirePackage{{booktabs}}\n\
\\RequirePackage{{enumitem}}\n\
\\RequirePackage{{hyperref}}\n\
{bibliography_setup}\
{extra}\
{watermark}\
{logo}\
{figure_widths}\
{headings}\
\\newtheorem{{tersetheorem}}{{Theorem}}\n\
\\newtheorem{{terseproposition}}{{Proposition}}\n\
\\newtheorem{{terselemma}}{{Lemma}}\n\
\\newtheorem{{tersedefinition}}{{Definition}}\n\
\\newtheorem{{terseexample}}{{Example}}\n\
\\newtheorem{{terseremark}}{{Remark}}\n\
\\newenvironment{{TerseEquation}}{{\\begin{{equation}}}}{{\\end{{equation}}}}\n\
\\newcommand{{\\TerseTitle}}[1]{{{{\\Huge\\bfseries #1\\par}}}}\n\
\\newcommand{{\\TerseSubtitle}}[1]{{{{\\Large #1\\par}}}}\n\
\\newcommand{{\\TerseAuthor}}[2]{{{{\\large #1\\par}}}}\n\
\\newcommand{{\\TerseAffiliation}}[1]{{{{\\normalsize #1\\par}}}}\n\
\\newcommand{{\\TerseDate}}[1]{{{{\\normalsize #1\\par}}}}\n\
\\newenvironment{{TerseAbstract}}{{\\par\\bigskip\\noindent\\textbf{{Abstract.}}\\ }}{{\\par\\bigskip}}\n\
\\newcommand{{\\TerseKeywords}}[1]{{{{\\noindent\\textit{{Keywords: }}#1\\par}}}}\n\
\\newcommand{{\\Terseref}}[1]{{\\ref{{#1}}}}\n",
        name = theme.name,
        font_package = font_package_for(&theme.body_font),
    )
}

pub fn generate_compile_instructions(theme: &ResolvedTheme) -> String {
    format!(
        "Compiling this project without Terse\n\
=====================================\n\
\n\
Theme: {name}\n\
\n\
Requires a TeX distribution providing XeLaTeX and Biber.\n\
\n\
  xelatex paper.tex\n\
  biber paper\n\
  xelatex paper.tex\n\
  xelatex paper.tex\n",
        name = theme.name,
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::semantic::{Author, Node, NodeKind};
    use crate::source::{FileId, SourceSpan};
    use crate::theme;

    fn span() -> SourceSpan {
        SourceSpan::new(FileId(0), 0, 0)
    }

    #[test]
    fn test_generate_document_is_deterministic_and_untimestamped() {
        let module = ParsedModule {
            file_id: FileId(0),
            metadata: Some(DocumentMetadata {
                title: "A Paper".to_string(),
                subtitle: None,
                authors: vec![Author {
                    name: "Ada Lovelace".to_string(),
                    affiliation: None,
                }],
                affiliations: vec![],
                date: None,
                language: "en".to_string(),
                abstract_blocks: vec![],
                keywords: vec![],
            }),
            references: vec![],
            blocks: vec![
                Node {
                    kind: NodeKind::Heading {
                        level: 1,
                        id: None,
                        inlines: vec![Inline::Text("Intro".to_string())],
                    },
                    span: span(),
                },
                Node {
                    kind: NodeKind::Paragraph {
                        inlines: vec![Inline::Text("50% done & counting.".to_string())],
                    },
                    span: span(),
                },
            ],
        };
        let theme = theme::academic();
        let out1 = generate_document(&module, &theme);
        let out2 = generate_document(&module, &theme);
        assert_eq!(out1, out2);
        assert!(out1.contains("\\TerseTitle{A Paper}"));
        assert!(out1.contains("\\TerseAuthor{Ada Lovelace}"));
        assert!(out1.contains("\\TerseHeadingOne{Intro}"));
        assert!(out1.contains("50\\% done \\& counting."));
        assert!(!out1.contains("\\today"));
    }
}
