//! LaTeX generation for the milestone-2 semantic subset (metadata, inline
//! markup, headings, paragraphs). No implicit dates, no absolute paths, no
//! timestamps: same module always produces the same bytes.

pub mod bibliography;
pub mod escape;
pub mod source_map;

use crate::semantic::{
    build_symbol_table, has_bibliography, Citation, CiteItem, DocumentMetadata, ListItem, Node, NodeKind,
    ParsedModule, SymbolKind, SymbolTable, TheoremKind,
};
use crate::syntax::inlines::Inline;
use crate::theme::ResolvedTheme;

pub const EMPTY_BIBLIOGRAPHY: &str = "";

pub fn generate_document(module: &ParsedModule, _theme: &ResolvedTheme) -> String {
    let symbols = build_symbol_table(module);
    let mut out = String::new();
    out.push_str("% Generated by terse. Do not edit by hand: the next successful build\n");
    out.push_str("% replaces this file. Copy it elsewhere to edit independently.\n");
    out.push_str("\\documentclass{article}\n");
    out.push_str("\\usepackage{terse-style}\n");
    if has_bibliography(module) {
        out.push_str("\\addbibresource{references.bib}\n");
    }
    if let Some(metadata) = &module.metadata {
        render_pdf_metadata(metadata, &mut out);
    }
    out.push_str("\\begin{document}\n");

    if let Some(metadata) = &module.metadata {
        render_title_material(metadata, &mut out);
    }

    render_nodes(&module.blocks, &symbols, &mut out);

    out.push_str("\\end{document}\n");
    out
}

/// PDF `/Title` and `/Author` document properties (`hyperref`'s
/// `\hypersetup`), distinct from the visible cover text rendered by
/// [`render_title_material`]: this is metadata a PDF viewer or search
/// index reads without opening the visible first page.
fn render_pdf_metadata(metadata: &DocumentMetadata, out: &mut String) {
    let authors: String = metadata
        .authors
        .iter()
        .map(|a| escape::escape_pdf_meta(&a.name))
        .collect::<Vec<_>>()
        .join(", ");
    out.push_str(&format!(
        "\\hypersetup{{pdftitle={{{}}},pdfauthor={{{}}}}}\n",
        escape::escape_pdf_meta(&metadata.title),
        authors
    ));
}

fn render_nodes(nodes: &[Node], symbols: &SymbolTable, out: &mut String) {
    for node in nodes {
        render_node(node, symbols, out);
    }
}

fn render_node(node: &Node, symbols: &SymbolTable, out: &mut String) {
    match &node.kind {
        NodeKind::Heading { level, id, inlines } => {
            let macro_name = match level {
                1 => "\\TerseHeadingOne",
                2 => "\\TerseHeadingTwo",
                _ => "\\TerseHeadingThree",
            };
            out.push_str(macro_name);
            out.push('{');
            render_inlines(inlines, symbols, out);
            out.push_str("}\n");
            if let Some(id) = id {
                out.push_str(&format!("\\phantomsection\\label{{{id}}}\n"));
            }
        }
        NodeKind::Paragraph { inlines } => {
            render_inlines(inlines, symbols, out);
            out.push_str("\n\n");
        }
        NodeKind::List { ordered, start, items } => render_list(*ordered, *start, items, symbols, out),
        NodeKind::Equation { numbered: false, payload, .. } => {
            out.push_str("\\[\n");
            out.push_str(payload);
            out.push_str("\n\\]\n");
        }
        NodeKind::Equation { id, payload, .. } => {
            out.push_str("\\begin{TerseEquation}");
            if let Some(id) = id {
                out.push_str(&format!("\\label{{{id}}}"));
            }
            out.push('\n');
            out.push_str(payload);
            out.push('\n');
            out.push_str("\\end{TerseEquation}\n");
        }
        NodeKind::Figure {
            path,
            id,
            role,
            caption,
            alt,
        } => {
            let is_wide = role.as_deref() == Some("wide");
            let env = if is_wide { "figure*" } else { "figure" };
            // Width is a theme-parameterized style macro, not a literal
            // number here, so switching themes never changes this file's
            // bytes: only `terse-style.sty` decides what each role means.
            let width_macro = if is_wide {
                "\\TerseFigureWideWidth"
            } else {
                "\\TerseFigureWidth"
            };
            // No placement argument and no literal alignment: both are
            // theme settings now, applied by `terse-style.sty` through
            // `\fps@figure` and `\TerseFigureAlign`, so this file's bytes
            // stay identical under every theme.
            out.push_str(&format!("\\begin{{{env}}}\n\\TerseFigureAlign\n"));
            out.push_str(&format!(
                "\\includegraphics[width={width_macro}]{{{}}}\n",
                escape::escape_url(path)
            ));
            out.push_str("\\caption{");
            render_inlines(caption, symbols, out);
            out.push_str("}\n");
            // Alt text has no visual LaTeX rendering; it is retained in the
            // semantic model for accessibility tooling built on top of the
            // generated PDF (not yet part of this milestone's backend).
            let _ = alt;
            if let Some(id) = id {
                out.push_str(&format!("\\label{{{id}}}\n"));
            }
            out.push_str(&format!("\\end{{{env}}}\n"));
        }
        NodeKind::Table {
            id,
            caption,
            header,
            rows,
        } => {
            let col_spec = "l".repeat(header.len());
            out.push_str("\\begin{table}\n\\TerseFigureAlign\n");
            out.push_str(&format!("\\begin{{tabular}}{{{col_spec}}}\n\\toprule\n"));
            out.push_str(&render_table_header_row(header));
            out.push_str(" \\\\\n\\midrule\n");
            for row in rows {
                out.push_str(&render_table_row(row));
                out.push_str(" \\\\\n");
            }
            out.push_str("\\bottomrule\n\\end{tabular}\n");
            out.push_str(&format!("\\caption{{{}}}\n", escape::escape_text(caption)));
            if let Some(id) = id {
                out.push_str(&format!("\\label{{{id}}}\n"));
            }
            out.push_str("\\end{table}\n");
        }
        NodeKind::TheoremLike { kind, title, id, body } => {
            let env = theorem_environment(*kind);
            out.push_str(&format!("\\begin{{{env}}}"));
            if let Some(title) = title {
                out.push('[');
                out.push_str(&escape::escape_optional_arg(title));
                out.push(']');
            }
            out.push('\n');
            if let Some(id) = id {
                out.push_str(&format!("\\label{{{id}}}\n"));
            }
            render_nodes(body, symbols, out);
            out.push_str(&format!("\\end{{{env}}}\n"));
        }
        NodeKind::RawTex { payload } => {
            // Opaque escape hatch: emitted byte-for-byte, never escaped or
            // otherwise rewritten. Portability is the author's
            // responsibility (task group 8's W-TEX-001 strict warning).
            out.push_str(payload);
            out.push('\n');
        }
        NodeKind::Proof { id, of, body } => {
            out.push_str("\\begin{proof}\n");
            if let Some(id) = id {
                out.push_str(&format!("\\label{{{id}}}\n"));
            }
            // `of` records an explicit theorem relationship without
            // inferring one from adjacency; amsthm's `proof` environment
            // has no built-in numbering hook for it, so it is retained as
            // a source comment for now.
            if let Some(of) = of {
                out.push_str(&format!("% proof of: {of}\n"));
            }
            render_nodes(body, symbols, out);
            out.push_str("\\end{proof}\n");
        }
        NodeKind::Bibliography => {
            out.push_str("\\printbibliography\n");
        }
    }
}

fn render_table_row(cells: &[String]) -> String {
    cells
        .iter()
        .map(|c| escape::escape_text(c))
        .collect::<Vec<_>>()
        .join(" & ")
}

/// Header cells go through a style-owned macro rather than a literal
/// `\textbf`: each cell is its own group in a `tabular`, so a row-level
/// font switch would only reach the first column. The macro name is fixed,
/// so these bytes are the same under every theme.
fn render_table_header_row(cells: &[String]) -> String {
    cells
        .iter()
        .map(|c| format!("\\TerseTableHeaderCell{{{}}}", escape::escape_text(c)))
        .collect::<Vec<_>>()
        .join(" & ")
}

/// The six theorem-like environments and their printed labels, in the
/// semantic model's kind order so a theme's `theorem_style` array lines up
/// index for index.
const THEOREM_ENVIRONMENTS: [(&str, &str); 6] = [
    ("tersetheorem", "Theorem"),
    ("terseproposition", "Proposition"),
    ("terselemma", "Lemma"),
    ("tersedefinition", "Definition"),
    ("terseexample", "Example"),
    ("terseremark", "Remark"),
];

fn theorem_environment(kind: TheoremKind) -> &'static str {
    match kind {
        TheoremKind::Theorem => "tersetheorem",
        TheoremKind::Proposition => "terseproposition",
        TheoremKind::Lemma => "terselemma",
        TheoremKind::Definition => "tersedefinition",
        TheoremKind::Example => "terseexample",
        TheoremKind::Remark => "terseremark",
    }
}

fn render_list(ordered: bool, start: Option<u32>, items: &[ListItem], symbols: &SymbolTable, out: &mut String) {
    let env = if ordered { "enumerate" } else { "itemize" };
    match (ordered, start) {
        (true, Some(n)) if n != 1 => out.push_str(&format!("\\begin{{{env}}}[start={n}]\n")),
        _ => out.push_str(&format!("\\begin{{{env}}}\n")),
    }
    for item in items {
        out.push_str("\\item ");
        render_inlines(&item.inlines, symbols, out);
        out.push('\n');
        render_nodes(&item.continuation, symbols, out);
    }
    out.push_str(&format!("\\end{{{env}}}\n"));
}

// Metadata renders in fixed semantic order: title, subtitle,
// authors/affiliations, explicit date, abstract, keywords, then body.
fn render_title_material(metadata: &DocumentMetadata, out: &mut String) {
    // One environment around all of the title material, so a theme can
    // decide the *layout* of the whole block (an inline paper title or a
    // cover page ending in `\clearpage`) without this file changing a byte
    // between themes. Individual macros can only carry sizes; a page break
    // has to belong to something that owns the block's end.
    out.push_str("\\begin{TerseTitleBlock}\n");
    out.push_str(&format!(
        "\\TerseTitle{{{}}}\n",
        escape::escape_text(&metadata.title)
    ));
    if let Some(subtitle) = &metadata.subtitle {
        out.push_str(&format!(
            "\\TerseSubtitle{{{}}}\n",
            escape::escape_text(subtitle)
        ));
    }
    for author in &metadata.authors {
        out.push_str(&format!(
            "\\TerseAuthor{{{}}}",
            escape::escape_text(&author.name)
        ));
        match &author.affiliation {
            Some(crate::semantic::Affiliation::Single(a)) => {
                out.push_str(&format!("{{{}}}", escape::escape_text(a)));
            }
            Some(crate::semantic::Affiliation::Multiple(list)) => {
                let joined = list
                    .iter()
                    .map(|a| escape::escape_text(a))
                    .collect::<Vec<_>>()
                    .join("; ");
                out.push_str(&format!("{{{joined}}}"));
            }
            None => out.push_str("{}"),
        }
        out.push('\n');
    }
    for affiliation in &metadata.affiliations {
        out.push_str(&format!(
            "\\TerseAffiliation{{{}}}\n",
            escape::escape_text(affiliation)
        ));
    }
    if let Some(date) = &metadata.date {
        out.push_str(&format!("\\TerseDate{{{}}}\n", escape::escape_text(date)));
    }
    // The block closes here, before the abstract: under the plain default
    // closing it runs `\maketitle`, which must precede `abstract`. The
    // order is the same under every theme, so the body stays theme-blind.
    out.push_str("\\end{TerseTitleBlock}\n");
    if !metadata.abstract_blocks.is_empty() {
        out.push_str("\\begin{TerseAbstract}\n");
        for paragraph in &metadata.abstract_blocks {
            render_inlines(paragraph, &SymbolTable::new(), out);
            out.push_str("\n\n");
        }
        out.push_str("\\end{TerseAbstract}\n");
    }
    if !metadata.keywords.is_empty() {
        let joined = metadata
            .keywords
            .iter()
            .map(|k| escape::escape_text(k))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!("\\TerseKeywords{{{joined}}}\n"));
    }
}

fn render_inlines(inlines: &[Inline], symbols: &SymbolTable, out: &mut String) {
    for inline in inlines {
        render_inline(inline, symbols, out);
    }
}

fn render_inline(inline: &Inline, symbols: &SymbolTable, out: &mut String) {
    match inline {
        Inline::Text(t) => out.push_str(&escape::escape_text(t)),
        Inline::Emphasis(v) => {
            out.push_str("\\emph{");
            render_inlines(v, symbols, out);
            out.push('}');
        }
        Inline::Strong(v) => {
            out.push_str("\\textbf{");
            render_inlines(v, symbols, out);
            out.push('}');
        }
        Inline::Code(t) => {
            out.push_str("\\texttt{");
            out.push_str(&escape::escape_text(t));
            out.push('}');
        }
        Inline::Link { label, destination } => {
            out.push_str("\\href{");
            out.push_str(&escape::escape_url(destination));
            out.push_str("}{");
            render_inlines(label, symbols, out);
            out.push('}');
        }
        Inline::Footnote(v) => {
            out.push_str("\\footnote{");
            render_inlines(v, symbols, out);
            out.push('}');
        }
        Inline::Math(t) => {
            out.push_str("\\(");
            out.push_str(t);
            out.push_str("\\)");
        }
        // A heading target has no visible number to point at, so its
        // cross-reference displays the heading's own title text as a
        // hyperlink instead of a numeric `\ref`; every other kind
        // resolves to an ordinary numbered reference. Cross-file
        // resolution is task group 12's extension of this same table.
        Inline::CrossRef(id) => match symbols.get(id) {
            Some(SymbolKind::Heading(title)) => {
                out.push_str("\\hyperref[");
                out.push_str(id);
                out.push_str("]{");
                render_inlines(title, symbols, out);
                out.push('}');
            }
            Some(SymbolKind::Numbered) | None => {
                out.push_str("\\Terseref{");
                out.push_str(id);
                out.push('}');
            }
        },
        Inline::Citation(citation) => render_citation(citation, out),
    }
}

fn locator_arg(item: &CiteItem) -> String {
    match &item.locator {
        Some(locator) => format!("[{}]", escape::escape_optional_arg(&locator.raw)),
        None => String::new(),
    }
}

fn render_citation(citation: &Citation, out: &mut String) {
    match citation {
        Citation::Narrative(alias) => {
            out.push_str("\\textcite{");
            out.push_str(alias);
            out.push('}');
        }
        // A single work uses BibLaTeX's ordinary `\cite[locator]{key}`;
        // more than one uses `\cites`, BibLaTeX's dedicated multicite
        // macro, so each work keeps its own independent locator rather
        // than sharing one postnote across a comma list.
        Citation::Group(items) if items.len() == 1 => {
            out.push_str("\\cite");
            out.push_str(&locator_arg(&items[0]));
            out.push('{');
            out.push_str(&items[0].alias);
            out.push('}');
        }
        Citation::Group(items) => {
            out.push_str("\\cites");
            for item in items {
                out.push_str(&locator_arg(item));
                out.push('{');
                out.push_str(&item.alias);
                out.push('}');
            }
        }
    }
}

/// Package names Terse recognizes as built-in declared support (`terse.toml`
/// `[latex] packages`). Each maps directly to a `\RequirePackage`; there is
/// no other declaration syntax for these, and unknown names are rejected by
/// [`validate_packages`] before this function is ever reached.
pub const BUILTIN_PACKAGES: &[&str] = &["tikz"];

/// Every package name [`generate_style`] can ever `\RequirePackage`, apart
/// from the theme's font package (those are listed by the export profile
/// under `fonts`): the always-loaded core set, the citation-build set, the
/// watermark set, and the closed built-in registry. The export profile's
/// `packages` list must equal this set exactly; a profile entry the
/// generator never emits would make `compiled-profile` claim more than it
/// checked, and an emitted package missing from the profile would make a
/// valid document fail export validation.
pub const STYLE_PACKAGES: &[&str] = &[
    "fontspec",
    "geometry",
    "xcolor",
    "amsmath",
    "amsthm",
    "graphicx",
    "booktabs",
    "enumitem",
    "hyperref",
    "babel",
    "biblatex",
    "eso-pic",
    "tikz",
];

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct UnknownPackage(pub String);

/// Validates declared `[latex] packages` entries against the closed
/// built-in registry, preserving authored order and rejecting duplicates
/// only implicitly (a package required twice is harmless, but an unknown
/// name always fails before any generation or engine invocation).
pub fn validate_packages(packages: &[String]) -> Result<Vec<&'static str>, UnknownPackage> {
    let mut out = Vec::new();
    for p in packages {
        match BUILTIN_PACKAGES.iter().find(|&&b| b == p) {
            Some(&name) => out.push(name),
            None => return Err(UnknownPackage(p.clone())),
        }
    }
    Ok(out)
}

/// The four TeX-distributed font files a body-font token selects, by
/// filename. The "Portable font and asset selection" requirement demands
/// selection *by filename*, never by family name: a family lookup goes
/// through the host's fontconfig database, which a fresh TeX installation
/// need not populate with TeX-tree fonts. Loading the package alone is not
/// enough, because a package like `tgheros` sets only `\sfdefault` and
/// leaves body text in the class default.
pub fn font_files_for(token: &str) -> [&'static str; 4] {
    match token {
        "tex-gyre-heros" => [
            "texgyreheros-regular.otf",
            "texgyreheros-bold.otf",
            "texgyreheros-italic.otf",
            "texgyreheros-bolditalic.otf",
        ],
        "tex-gyre-pagella" => [
            "texgyrepagella-regular.otf",
            "texgyrepagella-bold.otf",
            "texgyrepagella-italic.otf",
            "texgyrepagella-bolditalic.otf",
        ],
        "latin-modern" => [
            "lmroman10-regular.otf",
            "lmroman10-bold.otf",
            "lmroman10-italic.otf",
            "lmroman10-bolditalic.otf",
        ],
        // `libertinus-otf` and any future token default to Libertinus
        // Serif, the compiler default family.
        _ => [
            "LibertinusSerif-Regular.otf",
            "LibertinusSerif-Bold.otf",
            "LibertinusSerif-Italic.otf",
            "LibertinusSerif-BoldItalic.otf",
        ],
    }
}

/// Maps a theme's versioned, stable body-font token to the actual
/// TeX-distributed package name that provides it. The package still loads
/// alongside [`font_files_for`]'s `\setmainfont`, because these packages
/// also carry NFSS and math setup (`libertinus-otf` pulls `unicode-math`)
/// that dropping them would silently change.
pub fn font_package_for(token: &str) -> &'static str {
    match token {
        "tex-gyre-heros" => "tgheros",
        "tex-gyre-pagella" => "tgpagella",
        "latin-modern" => "lmodern",
        // `libertinus-otf` and any future token default to the compiler
        // default family, as [`font_files_for`] already does. No arm
        // returns its input: a theme string must never become a package
        // name, so this mapping is safe on its own rather than relying on
        // a validation check in another module.
        _ => "libertinus-otf",
    }
}

/// Maps a theme's heading-weight token to the LaTeX font-switch command
/// that applies it.
///
/// The token is deliberately semantic (`bold`, not `bfseries`): this value
/// is emitted immediately after a backslash inside a macro body, so
/// storing a command name would make the theme file the author of a
/// control sequence. It did, until `weight: bfseries\LaTeX{}` was shown to
/// land verbatim in the generated style. Every arm returns a literal, and
/// the default keeps a theme resolved by an older schema rendering as it
/// always has.
fn heading_weight_command(token: &str) -> &'static str {
    match token {
        "regular" => "\\mdseries",
        "italic" => "\\itshape",
        "small-caps" => "\\scshape",
        _ => "\\bfseries",
    }
}

/// Maps a theme's theorem-style token to the `amsthm` style it selects.
/// Same reasoning as [`heading_weight_command`]: the token reaches a macro
/// argument, so the mapping belongs here rather than depending on a closed
/// list enforced during resolution.
fn theorem_style_command(token: &str) -> &'static str {
    match token {
        "definition" => "definition",
        "remark" => "remark",
        _ => "plain",
    }
}

/// Maps a document's `language` metadata field (validated to `en` or
/// `pt-BR` during lowering) to the Babel/BibLaTeX language identifier
/// that selects hyphenation patterns and localized strings (bibliography
/// heading, date formatting) — never the running OS's installed locale.
fn babel_language_for(document_language: &str) -> &'static str {
    match document_language {
        "pt-BR" => "brazilian",
        _ => "english",
    }
}

pub fn generate_style(theme: &ResolvedTheme, extra_packages: &[&str], bibliography_language: Option<&str>) -> String {
    let extra: String = extra_packages
        .iter()
        .map(|p| format!("\\RequirePackage{{{p}}}\n"))
        .collect();
    // Biber only runs for citation builds (task 16.3): a module with no
    // bibliography never loads BibLaTeX/Babel at all, so it never depends
    // on Biber or locale hyphenation patterns it does not need.
    let bibliography_setup = match bibliography_language {
        Some(language) => format!(
            "\\RequirePackage[main={babel_lang}]{{babel}}\n\
\\RequirePackage[backend=biber,sorting=none,style={citation_style},language={babel_lang}]{{biblatex}}\n\
\\renewcommand*{{\\bibfont}}{{{bib_size}}}\n\
\\setlength{{\\bibitemsep}}{{{bib_sep}em}}\n",
            babel_lang = babel_language_for(language),
            // Bibliography typography can only be set where BibLaTeX is
            // actually loaded: a module with no citations never loads it.
            bib_size = match theme.bibliography_size.as_str() {
                "small" => "\\small",
                "footnotesize" => "\\footnotesize",
                _ => "\\normalsize",
            },
            bib_sep = theme.bibliography_item_spacing_em,
            // `sorting=none` keeps first-citation order in both styles; the
            // theme decides only how a citation is *rendered*.
            citation_style = match theme.citation_style.as_str() {
                "numeric" => "numeric",
                _ => "authoryear",
            },
        ),
        None => String::new(),
    };
    // Page geometry, only when the theme asks for it: with no page token
    // the class's own layout (letter) applies, which is the plain default.
    // A paper token alone must change *only* the paper, so it reproduces
    // the text block `size10.clo` computes for that paper (345pt wide on
    // any paper; 550pt tall on letter, 598pt on A4, measured against the
    // pinned engine) rather than `geometry`'s wider defaults. A margin
    // replaces the block, on the given paper or the class's.
    let geometry = match (theme.page_size.as_deref(), theme.page_margin_cm) {
        (None, None) => String::new(),
        (size, Some(margin)) => format!(
            "\\RequirePackage[{paper}margin={margin}cm]{{geometry}}\n",
            paper = match size {
                Some("letter") => "letterpaper,",
                Some(_) => "a4paper,",
                None => "",
            },
        ),
        (Some(size), None) => {
            let (paper, height) = if size == "letter" {
                ("letterpaper", "550pt")
            } else {
                ("a4paper", "598pt")
            };
            format!("\\RequirePackage[{paper},textwidth=345pt,textheight={height},centering]{{geometry}}\n")
        }
    };
    // Two-column is a class option, and the class line lives in the
    // theme-blind body, so the switch has to happen from the style file.
    // `\twocolumn` keeps LaTeX's native float machinery, which `multicol`
    // does not.
    let columns = if theme.page_columns == 2 {
        "\\AtBeginDocument{\\twocolumn}\n"
    } else {
        ""
    };
    // A font token is what loads `fontspec`; without one the kernel's own
    // family (Latin Modern under XeLaTeX, which the engine embeds without
    // any package) is the plain default.
    let font_setup = match theme.body_font.as_deref() {
        Some(token) => {
            let [regular, bold, italic, bold_italic] = font_files_for(token);
            format!(
                "\\RequirePackage{{fontspec}}\n\
\\RequirePackage{{{package}}}\n\
\\setmainfont{{{regular}}}[BoldFont={bold},ItalicFont={italic},BoldItalicFont={bold_italic}]\n",
                package = font_package_for(token),
            )
        }
        None => String::new(),
    };
    let body_color = format!(
        "\\definecolor{{TerseBodyColor}}{{HTML}}{{{hex}}}\n\\AtBeginDocument{{\\color{{TerseBodyColor}}}}\n",
        hex = theme.body_color.to_uppercase(),
    );
    // Float alignment and placement were literals in the body until this
    // change, which made them unreachable from a theme without breaking
    // the identical-body-bytes invariant. `\fps@figure`/`\fps@table` are
    // the class's own default-placement hooks, so the body can now emit
    // `\begin{figure}` with no optional argument at all.
    let figure_controls = format!(
        "\\newcommand{{\\TerseFigureAlign}}{{{align}}}\n\
\\newcommand{{\\TerseFigurePlacement}}{{{placement}}}\n\
\\makeatletter\n\\let\\fps@figure\\TerseFigurePlacement\n\\let\\fps@table\\TerseFigurePlacement\n\\makeatother\n",
        align = match theme.figure_align.as_str() {
            "left" => "\\raggedright",
            "right" => "\\raggedleft",
            _ => "\\centering",
        },
        placement = match theme.figure_placement.as_str() {
            "top" => "tbp",
            "bottom" => "bp",
            _ => "htbp",
        },
    );
    let watermark = if theme.watermark_kind == "none" {
        String::new()
    } else {
        let label = match theme.watermark_kind.as_str() {
            "draft" => "DRAFT",
            _ => "INTERNAL USE",
        };
        // A true alpha-blended watermark needs the `transparent` package,
        // which requires a pdfTeX-mode driver check that does not hold
        // under XeLaTeX in this toolchain; a light gray level (lower
        // opacity -> closer to white, i.e. fainter) gives the same
        // "visible but unobtrusive background furniture" effect without
        // that dependency.
        let gray_level = (1.0 - theme.watermark_opacity).clamp(0.0, 1.0);
        format!(
            "\\RequirePackage{{eso-pic}}\n\
\\AddToShipoutPictureBG{{\\AtPageCenter{{\\makebox(0,0){{\\rotatebox{{{angle}}}{{\\fontsize{{60}}{{60}}\\selectfont\\textcolor[gray]{{{gray_level}}}{{{label}}}}}}}}}}}\n",
            angle = theme.watermark_angle,
            gray_level = gray_level,
            label = label,
        )
    };
    let logo = match &theme.logo_path {
        Some(path) => format!(
            "\\newcommand{{\\TerseLogo}}{{\\includegraphics[width={pct}\\linewidth]{{{path}}}}}\n",
            pct = f64::from(theme.logo_width_pct) / 100.0,
        ),
        None => "\\newcommand{\\TerseLogo}{}\n".to_string(),
    };
    // Headings are the class's own sectioning commands: numbering, spacing
    // and the section counters come from `article`, so a document with no
    // theme reads like one written by hand. `none` is the unnumbered form
    // (the body's `\phantomsection\label` still gives it an anchor),
    // `roman` changes only the counter's presentation, and a non-default
    // weight re-issues the class's `\@startsection` definition
    // (`article.cls`, `\section`..`\subsubsection`) with the font argument
    // changed, which needs no package.
    let heading_macros = ["TerseHeadingOne", "TerseHeadingTwo", "TerseHeadingThree"];
    let section_commands = ["section", "subsection", "subsubsection"];
    let class_fonts = ["\\normalfont\\Large", "\\normalfont\\large", "\\normalfont\\normalsize"];
    let class_spacing = [
        ("{-3.5ex \\@plus -1ex \\@minus -.2ex}", "{2.3ex \\@plus.2ex}"),
        ("{-3.25ex\\@plus -1ex \\@minus -.2ex}", "{1.5ex \\@plus .2ex}"),
        ("{-3.25ex\\@plus -1ex \\@minus -.2ex}", "{1.5ex \\@plus .2ex}"),
    ];
    let mut headings = String::new();
    for i in 0..3 {
        let command = section_commands[i];
        let star = if theme.heading_numbering[i] == "none" { "*" } else { "" };
        headings.push_str(&format!(
            "\\newcommand{{\\{macro_name}}}[1]{{\\{command}{star}{{#1}}}}\n",
            macro_name = heading_macros[i],
        ));
        if theme.heading_numbering[i] == "roman" {
            let prefix = if i == 0 {
                String::new()
            } else {
                format!("\\the{}.", section_commands[i - 1])
            };
            headings.push_str(&format!(
                "\\renewcommand{{\\the{command}}}{{{prefix}\\Roman{{{command}}}}}\n"
            ));
        }
        if theme.heading_weight[i] != "bold" {
            let (before, after) = class_spacing[i];
            // Wrapped explicitly: an earlier block in this file ends with
            // `\makeatother`, so `@` is not a letter here by default.
            headings.push_str(&format!(
                "\\makeatletter\n\\renewcommand\\{command}{{\\@startsection{{{command}}}{{{level}}}{{\\z@}}{before}{after}{{{font}{weight}}}}}\n\\makeatother\n",
                level = i + 1,
                font = class_fonts[i],
                weight = heading_weight_command(&theme.heading_weight[i]),
            ));
        }
    }
    let figure_widths = format!(
        "\\newcommand{{\\TerseFigureWidth}}{{{default:.3}\\linewidth}}\n\\newcommand{{\\TerseFigureWideWidth}}{{{wide:.3}\\linewidth}}\n",
        default = f64::from(theme.figure_default_width_pct) / 100.0,
        wide = f64::from(theme.figure_wide_width_pct) / 100.0,
    );
    // The title block is the one place a theme controls page *layout*: the
    // cover variant opens with the logo and closes with a page break, and
    // is therefore also the only sensible invocation point for `\TerseLogo`.
    //
    // The plain default (paper layout, centered) is the class's own
    // `\maketitle`: the title macros collect `\title`/`\author`/`\date`
    // and the block runs `\maketitle` when it closes. Authors accumulate
    // into one list joined by `\and`, each on its own `tabular` cell the
    // way `article` lays them out, with the affiliation on a second line
    // when there is one. The date is cleared when the block opens so a
    // document with no date never gets `\today`. A cover, or a left-aligned
    // paper title, keeps the custom block: `\maketitle` can neither place a
    // logo nor end with a page break.
    // `\makeatletter` is explicit here because the figure controls above
    // end with `\makeatother`, which stops `@` being a letter for the rest
    // of this file.
    let title_block = if theme.title_layout == "paper" && theme.title_align == "center" {
        "\\makeatletter\n\
\\newenvironment{TerseTitleBlock}{\\date{}\\gdef\\TerseAuthorList{}}{\\maketitle}\n\
\\newcommand{\\TerseTitle}[1]{\\title{#1}}\n\
\\newcommand{\\TerseSubtitle}[1]{\\g@addto@macro\\@title{\\\\[0.5ex]\\large #1}}\n\
\\newcommand{\\TerseAuthor}[2]{%\n\
  \\ifx\\TerseAuthorList\\@empty\\else\\g@addto@macro\\TerseAuthorList{\\and}\\fi\n\
  \\g@addto@macro\\TerseAuthorList{#1}%\n\
  \\if\\relax\\detokenize{#2}\\relax\\else\\g@addto@macro\\TerseAuthorList{\\\\#2}\\fi\n\
  \\author{\\TerseAuthorList}}\n\
\\newcommand{\\TerseAffiliation}[1]{\\g@addto@macro\\TerseAuthorList{\\\\#1}\\author{\\TerseAuthorList}}\n\
\\newcommand{\\TerseDate}[1]{\\date{#1}}\n\
\\newenvironment{TerseAbstract}{\\begin{abstract}}{\\end{abstract}}\n\
\\makeatother\n"
            .to_string()
    } else {
        let title_align = if theme.title_align == "left" {
            "\\raggedright"
        } else {
            "\\centering"
        };
        let block = if theme.title_layout == "cover" {
            format!(
                "\\newenvironment{{TerseTitleBlock}}\
{{\\begingroup{title_align}\\vspace*{{2cm}}\\TerseLogo\\par\\bigskip}}\
{{\\par\\endgroup\\clearpage}}\n"
            )
        } else {
            format!(
                "\\newenvironment{{TerseTitleBlock}}\
{{\\begingroup{title_align}}}\
{{\\par\\endgroup\\bigskip}}\n"
            )
        };
        block
            + "\\newcommand{\\TerseTitle}[1]{{\\Huge\\bfseries #1\\par}}\n\
\\newcommand{\\TerseSubtitle}[1]{{\\Large #1\\par}}\n\
\\newcommand{\\TerseAuthor}[2]{{\\large #1\\par}\\if\\relax\\detokenize{#2}\\relax\\else{\\normalsize #2\\par}\\fi}\n\
\\newcommand{\\TerseAffiliation}[1]{{\\normalsize #1\\par}}\n\
\\newcommand{\\TerseDate}[1]{{\\normalsize #1\\par}}\n\
\\newenvironment{TerseAbstract}{\\par\\bigskip\\noindent\\textbf{Abstract.}\\ }{\\par\\bigskip}\n"
    };
    let theorem_setup: String = THEOREM_ENVIRONMENTS
        .iter()
        .zip(theme.theorem_style.iter())
        .map(|((env, label), style)| {
            format!(
                "\\theoremstyle{{{style}}}\n\\newtheorem{{{env}}}{{{label}}}\n",
                style = theorem_style_command(style)
            )
        })
        .collect();
    let table_setup = format!(
        "\\renewcommand{{\\arraystretch}}{{{padding}}}\n\
\\newcommand{{\\TerseTableHeaderCell}}[1]{{{header}}}\n{rules}",
        padding = theme.table_padding,
        header = if theme.table_header == "plain" { "#1" } else { "\\textbf{#1}" },
        // `booktabs` is always loaded; the `plain` choice maps its rules
        // onto the classic `\hline` rather than dropping them, so a table
        // never silently loses its structure.
        rules = if theme.table_rules == "plain" {
            "\\let\\toprule\\hline\n\\let\\midrule\\hline\n\\let\\bottomrule\\hline\n"
        } else {
            ""
        },
    );
    format!(
        "% Generated by terse for theme '{name}'. Do not edit by hand.\n\
\\NeedsTeXFormat{{LaTeX2e}}\n\
\\ProvidesPackage{{terse-style}}\n\
{font_setup}\
{geometry}\
\\RequirePackage{{xcolor}}\n\
\\RequirePackage{{amsmath}}\n\
\\RequirePackage{{amsthm}}\n\
\\RequirePackage{{graphicx}}\n\
\\RequirePackage{{booktabs}}\n\
\\RequirePackage{{enumitem}}\n\
\\RequirePackage{{hyperref}}\n\
{bibliography_setup}\
{extra}\
{body_color}\
{columns}\
{watermark}\
{logo}\
{figure_widths}\
{figure_controls}\
{table_setup}\
{headings}\
{theorem_setup}\
\\newenvironment{{TerseEquation}}{{\\begin{{equation}}}}{{\\end{{equation}}}}\n\
{title_block}\
\\newcommand{{\\TerseKeywords}}[1]{{{{\\noindent\\textit{{Keywords: }}#1\\par}}}}\n\
\\newcommand{{\\Terseref}}[1]{{\\ref{{#1}}}}\n",
        name = theme.name,
    )
}

pub fn generate_compile_instructions(theme: &ResolvedTheme) -> String {
    format!(
        "Compiling this project without Terse\n\
=====================================\n\
\n\
Theme: {name}\n\
\n\
Requires a TeX distribution providing XeLaTeX and Biber.\n\
\n\
  xelatex paper.tex\n\
  biber paper\n\
  xelatex paper.tex\n\
  xelatex paper.tex\n",
        name = theme.name,
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::semantic::{Author, Node, NodeKind};
    use crate::source::{FileId, SourceSpan};
    use crate::theme;

    fn span() -> SourceSpan {
        SourceSpan::new(FileId(0), 0, 0)
    }

    /// Runs the real front end (lex, block parse, lower) so generation
    /// tests can start from `.trs` text rather than hand-built nodes.
    fn parse_src(text: &str) -> ParsedModule {
        let file = crate::source::SourceFile::new(FileId(0), "entry.trs", text.as_bytes().to_vec()).unwrap();
        let lines = crate::syntax::lexer::lex_lines(file.text()).unwrap();
        let blocks = crate::syntax::blocks::parse_module(&lines, file.text(), file.id, file.base_offset()).unwrap();
        crate::semantic::lower(blocks, file.id).unwrap()
    }

    fn body_of(text: &str) -> String {
        let out = generate_document(&parse_src(text), &theme::academic());
        let start = out.find("\\begin{document}").expect("document begins");
        out[start..].to_string()
    }

    #[test]
    fn test_dollar_inline_math_generates_like_paren_math() {
        let dollar = body_of("document:\n  title: \"T\"\n\nSo $\\frac{a}{b}$ holds.\n");
        let paren = body_of("document:\n  title: \"T\"\n\nSo \\(\\frac{a}{b}\\) holds.\n");
        assert_eq!(dollar, paren);
        assert!(dollar.contains("\\frac{a}{b}"));
    }

    #[test]
    fn test_unnumbered_dollar_display_emits_brackets() {
        let body = body_of(concat!(
            "document:\n  title: \"T\"\n\n",
            "math [id: eq-a]:\n  a = 1\n\n",
            "$$ x $$\n\n",
            "math [id: eq-b]:\n  b = 2\n",
        ));
        let a = body.find("\\label{eq-a}").expect("eq-a");
        let x = body.find("\\[\n x \n\\]\n").expect("bracketed $$ display");
        let b = body.find("\\label{eq-b}").expect("eq-b");
        assert!(a < x && x < b, "{body}");
        assert_eq!(body.matches("\\begin{TerseEquation}").count(), 2, "{body}");
    }

    #[test]
    fn test_currency_dollars_are_escaped_in_output() {
        let body = body_of("document:\n  title: \"T\"\n\nIt costs $5 to $10 per unit.\n");
        assert!(body.contains("It costs \\$5 to \\$10 per unit."), "{body}");
        assert!(!body.contains("\\("), "{body}");
    }

    #[test]
    fn test_generate_document_is_deterministic_and_untimestamped() {
        let module = ParsedModule {
            file_id: FileId(0),
            metadata: Some(DocumentMetadata {
                title: "A Paper".to_string(),
                subtitle: None,
                authors: vec![Author {
                    name: "Ada Lovelace".to_string(),
                    affiliation: None,
                }],
                affiliations: vec![],
                date: None,
                language: "en".to_string(),
                abstract_blocks: vec![],
                keywords: vec![],
            }),
            references: vec![],
            blocks: vec![
                Node {
                    kind: NodeKind::Heading {
                        level: 1,
                        id: None,
                        inlines: vec![Inline::Text("Intro".to_string())],
                    },
                    span: span(),
                },
                Node {
                    kind: NodeKind::Paragraph {
                        inlines: vec![Inline::Text("50% done & counting.".to_string())],
                    },
                    span: span(),
                },
            ],
        };
        let theme = theme::academic();
        let out1 = generate_document(&module, &theme);
        let out2 = generate_document(&module, &theme);
        assert_eq!(out1, out2);
        assert!(out1.contains("\\TerseTitle{A Paper}"));
        assert!(out1.contains("\\TerseAuthor{Ada Lovelace}"));
        assert!(out1.contains("\\TerseHeadingOne{Intro}"));
        assert!(out1.contains("50\\% done \\& counting."));
        assert!(!out1.contains("\\today"));
    }

    fn resolve_str(text: &str) -> ResolvedTheme {
        let file = crate::source::SourceFile::new(FileId(0), "t.theme", text.as_bytes().to_vec()).unwrap();
        theme::resolve_theme("academic", &file).expect("test theme resolves")
    }

    fn metadata_module(date: Option<&str>, subtitle: Option<&str>) -> ParsedModule {
        ParsedModule {
            file_id: FileId(0),
            metadata: Some(DocumentMetadata {
                title: "A Paper".to_string(),
                subtitle: subtitle.map(str::to_string),
                authors: vec![
                    Author {
                        name: "Ada Lovelace".to_string(),
                        affiliation: Some(crate::semantic::Affiliation::Single("Analytical Engines".to_string())),
                    },
                    Author {
                        name: "Charles Babbage".to_string(),
                        affiliation: None,
                    },
                ],
                affiliations: vec![],
                date: date.map(str::to_string),
                language: "en".to_string(),
                abstract_blocks: vec![vec![Inline::Text("An abstract.".to_string())]],
                keywords: vec!["engines".to_string()],
            }),
            references: vec![],
            blocks: vec![],
        }
    }

    // ----- plain-latex-default: style emission -----

    /// Scenario "No theme is the plain article": with no font or page
    /// token the style loads neither `fontspec` nor `geometry`, while the
    /// always-loaded content packages stay (they do not change the look
    /// and keep the body theme-blind).
    #[test]
    fn test_default_style_has_no_font_or_geometry() {
        let style = generate_style(&theme::academic(), &[], None);
        for absent in ["fontspec", "\\setmainfont", "geometry", "libertinus", "lmodern", "tgheros"] {
            assert!(!style.contains(absent), "plain default must not emit {absent}:\n{style}");
        }
        for present in ["hyperref", "amsthm", "graphicx", "booktabs", "amsmath", "enumitem"] {
            assert!(style.contains(&format!("\\RequirePackage{{{present}}}")), "{present} stays loaded");
        }
    }

    /// A font token is what pulls `fontspec`, the font package and the
    /// filename-based `\setmainfont`.
    #[test]
    fn test_font_token_pulls_fontspec() {
        let style = generate_style(&resolve_str("body:\n  font: libertinus-otf\n"), &[], None);
        assert!(style.contains("\\RequirePackage{fontspec}"));
        assert!(style.contains("\\RequirePackage{libertinus-otf}"));
        assert!(style.contains("\\setmainfont{LibertinusSerif-Regular.otf}"));
        let fontspec_at = style.find("\\RequirePackage{fontspec}").unwrap();
        let font_pkg_at = style.find("\\RequirePackage{libertinus-otf}").unwrap();
        let main_at = style.find("\\setmainfont").unwrap();
        assert!(fontspec_at < font_pkg_at && font_pkg_at < main_at, "fontspec, package, then \\setmainfont");
    }

    /// Scenario "Page size alone changes only the paper": a size-only
    /// theme reproduces the class's own text block on that paper (345pt
    /// wide; 550pt tall on letter, 598pt on A4, as `size10.clo` computes
    /// them), and a margin overrides the block instead.
    #[test]
    fn test_page_size_alone_reproduces_class_layout() {
        let plain = generate_style(&theme::academic(), &[], None);
        let a4 = generate_style(&resolve_str("page:\n  size: a4\n"), &[], None);
        let a4_line = "\\RequirePackage[a4paper,textwidth=345pt,textheight=598pt,centering]{geometry}\n";
        assert!(a4.contains(a4_line), "got:\n{a4}");
        assert_eq!(a4.replace(a4_line, ""), plain, "the geometry line is the only difference");

        let letter = generate_style(&resolve_str("page:\n  size: letter\n"), &[], None);
        assert!(letter.contains("[letterpaper,textwidth=345pt,textheight=550pt,centering]{geometry}"));

        let margin_only = generate_style(&resolve_str("page:\n  margin: 2.5cm\n"), &[], None);
        assert!(margin_only.contains("\\RequirePackage[margin=2.5cm]{geometry}"), "got:\n{margin_only}");
        assert!(!margin_only.contains("textwidth"));

        let both = generate_style(&resolve_str("page:\n  size: a4\n  margin: 2.5cm\n"), &[], None);
        assert!(both.contains("\\RequirePackage[a4paper,margin=2.5cm]{geometry}"), "got:\n{both}");
        assert!(!both.contains("textwidth"));
    }

    // ----- plain-latex-default: headings -----

    /// Scenario "No theme is the plain article": headings are the class's
    /// own sectioning commands, with no private counters or font switches.
    #[test]
    fn test_headings_delegate_to_sectioning_commands() {
        let style = generate_style(&theme::academic(), &[], None);
        assert!(style.contains("\\newcommand{\\TerseHeadingOne}[1]{\\section{#1}}"), "got:\n{style}");
        assert!(style.contains("\\newcommand{\\TerseHeadingTwo}[1]{\\subsection{#1}}"));
        assert!(style.contains("\\newcommand{\\TerseHeadingThree}[1]{\\subsubsection{#1}}"));
        assert!(!style.contains("\\newcounter{terseheading"));
        assert!(!style.contains("\\selectfont "));
        assert!(!style.contains("\\@startsection"), "the class definition is untouched by default");
    }

    /// Scenario "Heading numbering is disabled": the unnumbered form; the
    /// body's own `\phantomsection\label` keeps the anchor.
    #[test]
    fn test_numbering_none_uses_starred_form() {
        let style = generate_style(&resolve_str("heading.1:\n  numbering: none\n"), &[], None);
        assert!(style.contains("\\newcommand{\\TerseHeadingOne}[1]{\\section*{#1}}"), "got:\n{style}");
        assert!(style.contains("\\newcommand{\\TerseHeadingTwo}[1]{\\subsection{#1}}"), "other levels unchanged");
    }

    #[test]
    fn test_numbering_roman_redefines_thesection() {
        let style = generate_style(&resolve_str("heading.1:\n  numbering: roman\n"), &[], None);
        assert!(style.contains("\\renewcommand{\\thesection}{\\Roman{section}}"), "got:\n{style}");
        assert!(!style.contains("\\thesubsection"), "only the level that asked for it");

        let level_two = generate_style(&resolve_str("heading.2:\n  numbering: roman\n"), &[], None);
        assert!(
            level_two.contains("\\renewcommand{\\thesubsection}{\\thesection.\\Roman{subsection}}"),
            "the parent prefix is kept:\n{level_two}"
        );
        assert!(!generate_style(&theme::academic(), &[], None).contains("\\renewcommand{\\thesection}"));
    }

    /// A non-default weight re-issues the class's `\@startsection`
    /// definition with the font argument changed; no package is added.
    #[test]
    fn test_heading_weight_redefines_startsection() {
        let style = generate_style(&resolve_str("heading.1:\n  weight: italic\n"), &[], None);
        assert!(
            style.contains("\\renewcommand\\section{\\@startsection{section}{1}{\\z@}"),
            "got:\n{style}"
        );
        assert!(style.contains("{\\normalfont\\Large\\itshape}}"));
        assert!(!style.contains("\\renewcommand\\subsection"), "only the level that asked for it");
        assert!(!style.contains("titlesec"));

        let bold = generate_style(&resolve_str("heading.1:\n  weight: bold\n"), &[], None);
        assert!(!bold.contains("\\@startsection"), "bold is the class default");
    }

    // ----- plain-latex-default: title block -----

    /// Scenario "Default title block is maketitle".
    #[test]
    fn test_paper_title_block_uses_maketitle() {
        let style = generate_style(&theme::academic(), &[], None);
        assert!(
            style.contains("\\newenvironment{TerseTitleBlock}{\\date{}"),
            "the block opens by clearing the date so \\maketitle never inserts \\today:\n{style}"
        );
        assert!(style.contains("{\\maketitle}"), "the block closes with \\maketitle");
        assert!(style.contains("\\newcommand{\\TerseTitle}[1]{\\title{#1}}"));
        assert!(style.contains("\\newcommand{\\TerseDate}[1]{\\date{#1}}"));
        assert!(style.contains("\\newenvironment{TerseAbstract}{\\begin{abstract}}{\\end{abstract}}"));
        // Authors accumulate into `\author`, separated by `\and`, each
        // carrying its affiliation on a new line when it has one.
        assert!(style.contains("\\and"), "authors are joined with \\and");
        assert!(style.contains("\\if\\relax\\detokenize{#2}\\relax"), "an empty affiliation appends nothing");
        assert!(!style.contains("\\Huge\\bfseries"), "no hand-made title typography by default");
        // The subtitle joins the title.
        assert!(style.contains("\\g@addto@macro\\@title{\\\\[0.5ex]\\large #1}"), "got:\n{style}");
    }

    #[test]
    fn test_missing_date_emits_no_today() {
        let body = generate_document(&metadata_module(None, None), &theme::academic());
        let style = generate_style(&theme::academic(), &[], None);
        assert!(!body.contains("\\today"));
        assert!(!style.contains("\\today"));
        assert!(!body.contains("\\TerseDate"), "no date macro for a dateless document");
        let dated = generate_document(&metadata_module(Some("1843-01-01"), None), &theme::academic());
        assert!(dated.contains("\\TerseDate{1843-01-01}"));
    }

    /// The cover layout, and a left-aligned paper title, keep the custom
    /// block: `\maketitle` cannot place a logo or end with a page break.
    #[test]
    fn test_cover_layout_keeps_custom_block() {
        let cover = generate_style(&resolve_str("title:\n  layout: cover\n"), &[], None);
        assert!(cover.contains("\\vspace*{2cm}\\TerseLogo\\par\\bigskip"), "got:\n{cover}");
        assert!(cover.contains("\\clearpage"));
        assert!(cover.contains("\\newcommand{\\TerseTitle}[1]{{\\Huge\\bfseries #1\\par}}"));
        assert!(!cover.contains("\\maketitle"));

        let left = generate_style(&resolve_str("title:\n  align: left\n"), &[], None);
        assert!(left.contains("\\raggedright"), "got:\n{left}");
        assert!(!left.contains("\\maketitle"));
    }

    /// Design D5: the abstract and keywords follow the title block, because
    /// `\maketitle` must run before `abstract`. Identical under every theme.
    #[test]
    fn test_abstract_follows_title_block() {
        let module = metadata_module(Some("1843-01-01"), Some("A Subtitle"));
        let body = generate_document(&module, &theme::academic());
        let end_block = body.find("\\end{TerseTitleBlock}").expect("block closes");
        let abstract_at = body.find("\\begin{TerseAbstract}").expect("abstract present");
        let keywords_at = body.find("\\TerseKeywords{engines}").expect("keywords present");
        let date_at = body.find("\\TerseDate{1843-01-01}").expect("date present");
        assert!(date_at < end_block, "date is inside the block");
        assert!(end_block < abstract_at && abstract_at < keywords_at, "got:\n{body}");
        assert!(body.contains("\\TerseAuthor{Ada Lovelace}{Analytical Engines}"));
        assert!(body.contains("\\TerseAuthor{Charles Babbage}{}"));
        assert!(body.contains("\\TerseSubtitle{A Subtitle}"));

        let cover = resolve_str("title:\n  layout: cover\n");
        assert_eq!(body, generate_document(&module, &cover), "the body is theme-blind");
    }
}
