//! Maps generated `paper.tex` line numbers back to original `.trs`
//! source spans, so an engine log line (`paper.tex:42`) can be reported
//! as the original author-visible position instead of a generated one.
//!
//! Granularity: one interval per top-level body node (paragraph, raw TeX
//! block, math/equation, bibliography position, etc). A generated line
//! inside the preamble, or produced by theme/style parameters rather
//! than authored content, has no interval at all — [`SourceMap::locate`]
//! returns `None` for it rather than inventing a span, which is exactly
//! the "unmappable stays generated" contract.

use crate::semantic::{build_symbol_table, ParsedModule};
use crate::source::SourceSpan;
use crate::theme::ResolvedTheme;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Origin {
    /// Content traced to a specific byte range of a specific original
    /// module (the entry or an included `.trs` file — [`SourceSpan`]
    /// already carries the correct [`crate::source::FileId`] for
    /// included content, since each module is parsed with its own id
    /// before expansion).
    Source(SourceSpan),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct GeneratedInterval {
    /// 1-based, inclusive, matching how TeX engines report line numbers.
    pub start_line: usize,
    pub end_line: usize,
    pub origin: Origin,
}

#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct SourceMap {
    intervals: Vec<GeneratedInterval>,
}

impl SourceMap {
    /// Returns the original span whose generated interval contains
    /// `line`, or `None` if that line falls in the preamble, postamble,
    /// or any other generated scaffolding no interval claims.
    pub fn locate(&self, line: usize) -> Option<SourceSpan> {
        self.intervals
            .iter()
            .find(|i| line >= i.start_line && line <= i.end_line)
            .map(|i| match i.origin {
                Origin::Source(span) => span,
            })
    }
}

fn count_lines(text: &str) -> usize {
    text.matches('\n').count()
}

/// Renders the same bytes [`super::generate_document`] would, alongside a
/// [`SourceMap`] built at top-level-node granularity. Kept as a separate
/// entrypoint (rather than always computing a map) since most callers
/// (ordinary builds without an engine failure to diagnose) never need it.
pub fn generate_document_with_map(module: &ParsedModule, _theme: &ResolvedTheme) -> (String, SourceMap) {
    let symbols = build_symbol_table(module);

    let mut preamble = String::new();
    preamble.push_str("% Generated by terse. Do not edit by hand: the next successful build\n");
    preamble.push_str("% replaces this file. Copy it elsewhere to edit independently.\n");
    preamble.push_str("\\documentclass{article}\n");
    preamble.push_str("\\usepackage{terse-style}\n");
    if crate::semantic::has_bibliography(module) {
        preamble.push_str("\\addbibresource{references.bib}\n");
    }
    if let Some(metadata) = &module.metadata {
        super::render_pdf_metadata(metadata, &mut preamble);
    }
    preamble.push_str("\\begin{document}\n");
    if let Some(metadata) = &module.metadata {
        super::render_title_material(metadata, &mut preamble);
    }

    let mut body = String::new();
    let mut intervals = Vec::new();
    let mut line = count_lines(&preamble) + 1;
    for node in &module.blocks {
        let mut rendered = String::new();
        super::render_nodes(std::slice::from_ref(node), &symbols, &mut rendered);
        let added = count_lines(&rendered);
        if added > 0 {
            intervals.push(GeneratedInterval {
                start_line: line,
                end_line: line + added - 1,
                origin: Origin::Source(node.span),
            });
        }
        line += added;
        body.push_str(&rendered);
    }

    let mut out = preamble;
    out.push_str(&body);
    out.push_str("\\end{document}\n");

    (out, SourceMap { intervals })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::semantic::{DocumentMetadata, Node, NodeKind};
    use crate::source::FileId;
    use crate::theme;

    fn span(file: u32, start: u32) -> SourceSpan {
        SourceSpan::new(FileId(file), start, start + 1)
    }

    fn metadata() -> DocumentMetadata {
        DocumentMetadata {
            title: "T".to_string(),
            subtitle: None,
            authors: vec![],
            affiliations: vec![],
            date: None,
            language: "en".to_string(),
            abstract_blocks: vec![],
            keywords: vec![],
        }
    }

    #[test]
    fn test_included_spans_survive_generation() {
        // One node "from" the entry (file 0), one "from" an included
        // module (file 1) — the map must keep each interval's own file
        // id, proving included content is not attributed to the entry.
        let module = ParsedModule {
            file_id: FileId(0),
            metadata: Some(metadata()),
            references: vec![],
            blocks: vec![
                Node { kind: NodeKind::RawTex { payload: "\\relax".to_string() }, span: span(0, 10) },
                Node { kind: NodeKind::RawTex { payload: "\\relax".to_string() }, span: span(1, 20) },
            ],
        };
        let (_text, map) = generate_document_with_map(&module, &theme::academic());
        let first = map.intervals[0];
        let second = map.intervals[1];
        assert_eq!(first.origin, Origin::Source(span(0, 10)));
        assert_eq!(second.origin, Origin::Source(span(1, 20)));
    }

    #[test]
    fn test_unmapped_preamble_line_returns_none() {
        let module = ParsedModule { file_id: FileId(0), metadata: None, references: vec![], blocks: vec![] };
        let (_text, map) = generate_document_with_map(&module, &theme::academic());
        assert_eq!(map.locate(1), None, "the preamble is generated scaffolding, not authored content");
    }

    #[test]
    fn test_generated_text_matches_ordinary_generation() {
        let module = ParsedModule {
            file_id: FileId(0),
            metadata: Some(metadata()),
            references: vec![],
            blocks: vec![Node {
                kind: NodeKind::Paragraph { inlines: vec![crate::syntax::inlines::Inline::Text("hi".to_string())] },
                span: span(0, 5),
            }],
        };
        let theme = theme::academic();
        let (mapped_text, _map) = generate_document_with_map(&module, &theme);
        let plain_text = super::super::generate_document(&module, &theme);
        assert_eq!(mapped_text, plain_text);
    }
}
