//! `terse init`: preflighted, whole-tree scaffold creation.

use std::fs;
use std::path::{Path, PathBuf};

const MANIFEST_TEMPLATE: &str = "format-version = 1\n\
\n\
[project]\n\
entry = \"paper.trs\"\n\
output = \"build\"\n\
\n\
[themes]\n\
academic = \"themes/academic.theme\"\n\
\n\
[latex]\n\
engine = \"xelatex\"\n\
pdf = \"auto\"\n\
\n\
[references]\n\
lockfile = \"references.lock\"\n";

const ENTRY_TEMPLATE: &str = "document:\n  title: \"Untitled Paper\"\n\n# Introduction\n\nStart writing here.\n";

const ACADEMIC_THEME_TEMPLATE: &str =
    "// Generated by `terse init`. Presentation settings for the academic theme.\n";

const LOCKFILE_TEMPLATE: &str = "lock-version = 1\nnormalization-version = 1\n\n[entries]\n";

const IGNORE_BLOCK: &[&str] = &["/build", "/.terse-cache"];

pub fn run_init(cwd: &Path, directory: Option<&Path>, force: bool) -> i32 {
    let target = match directory {
        Some(d) => cwd.join(d),
        None => cwd.to_path_buf(),
    };
    if let Err(e) = fs::create_dir_all(&target) {
        eprintln!("error: cannot create directory {}: {e}", target.display());
        return 3;
    }

    let scaffold: Vec<(PathBuf, &str)> = vec![
        (target.join("terse.toml"), MANIFEST_TEMPLATE),
        (target.join("paper.trs"), ENTRY_TEMPLATE),
        (
            target.join("themes").join("academic.theme"),
            ACADEMIC_THEME_TEMPLATE,
        ),
        (target.join("references.lock"), LOCKFILE_TEMPLATE),
    ];

    if !force {
        for (path, _) in &scaffold {
            if path.exists() {
                eprintln!(
                    "error[E-CONFIG-006]: '{}' already exists; pass --force to overwrite scaffold files",
                    path.display()
                );
                return 2;
            }
        }
    }

    for (path, contents) in &scaffold {
        if let Some(parent) = path.parent() {
            if let Err(e) = fs::create_dir_all(parent) {
                eprintln!("error: cannot create directory {}: {e}", parent.display());
                return 3;
            }
        }
        if let Err(e) = fs::write(path, contents) {
            eprintln!("error: cannot write {}: {e}", path.display());
            return 3;
        }
    }

    if let Err(e) = merge_gitignore(&target.join(".gitignore")) {
        eprintln!("error: cannot update .gitignore: {e}");
        return 3;
    }

    println!("initialized a Terse project in {}", target.display());
    0
}

/// Adds the required build/cache ignore rules without touching or
/// reordering any existing unrelated entries.
fn merge_gitignore(path: &Path) -> std::io::Result<()> {
    let existing = fs::read_to_string(path).unwrap_or_default();
    let mut lines: Vec<String> = existing.lines().map(str::to_string).collect();
    for entry in IGNORE_BLOCK {
        if !lines.iter().any(|l| l.trim() == *entry) {
            lines.push((*entry).to_string());
        }
    }
    let mut out = lines.join("\n");
    if !out.is_empty() {
        out.push('\n');
    }
    fs::write(path, out)
}
