//! Engine-log-to-source mapping: a generated line inside authored/included
//! content must map back to its original span; a line the map has no
//! interval for (preamble, or genuinely unmappable engine scaffolding)
//! must stay generated rather than inventing a fake span.

use crate::latex::source_map::generate_document_with_map;
use crate::semantic::{Node, NodeKind, ParsedModule};
use crate::source::FileId;
use crate::syntax::inlines::Inline;
use crate::theme;

fn span(file: u32, start: u32) -> crate::source::SourceSpan {
    crate::source::SourceSpan::new(FileId(file), start, start + 1)
}

#[test]
fn test_engine_error_maps_to_included_raw_source() {
    // A raw TeX block that came from an included module (file id 1, not
    // the entry's file id 0) must map back to *that* file, proving an
    // engine error on its generated line is reported against the
    // original included `.trs`, not the entry.
    let module = ParsedModule {
        file_id: FileId(0),
        metadata: None,
        references: vec![],
        blocks: vec![
            Node {
                kind: NodeKind::Paragraph { inlines: vec![Inline::Text("intro".to_string())] },
                span: span(0, 1),
            },
            Node { kind: NodeKind::RawTex { payload: "\\badcommand".to_string() }, span: span(1, 42) },
        ],
    };
    let (text, map) = generate_document_with_map(&module, &theme::academic());

    let raw_line = text
        .lines()
        .enumerate()
        .find(|(_, l)| l.contains("\\badcommand"))
        .map(|(i, _)| i + 1)
        .expect("raw payload must appear verbatim in generated output");

    let origin = map.locate(raw_line).expect("the raw block's line must be mapped");
    assert_eq!(origin.file_id, FileId(1), "must point at the included module, not the entry");
}

#[test]
fn test_unmappable_error_stays_generated() {
    let module = ParsedModule { file_id: FileId(0), metadata: None, references: vec![], blocks: vec![] };
    let (text, map) = generate_document_with_map(&module, &theme::academic());

    // Line 1 is always generated preamble scaffolding ("% Generated by
    // terse...") with no authored counterpart at all.
    assert!(text.starts_with("% Generated by terse"));
    assert_eq!(map.locate(1), None, "generated scaffolding must never be reported as a fake source span");
}
